name: e2e Test
on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
env:
  INFURA_KEY: ${{ secrets.INFURA_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn build
          yarn test:ci
